### ISSUE TITLE
doesn't work with node

### ISSUE THREAD

**Issue by danielb2** [coffeedriven/card.js#2]
``` bash
[~/tmp]$ node --version
v0.12.2

[~/tmp]$ node
> require('card');
ReferenceError: document is not defined
    at module.exports (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1078:31)
    at Object.sassify (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1977:24986)
    at s (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1:573)
    at /Users/daniel/tmp/node_modules/card/lib/js/card.js:1:624
    at Object.<anonymous> (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1115:1)
    at Object.../scss/card.scss (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1433:4)
    at s (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1:573)
    at e (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1:744)
    at /Users/daniel/tmp/node_modules/card/lib/js/card.js:1:762
    at a (/Users/daniel/tmp/node_modules/card/lib/js/card.js:1:119)
```

**Comment by coffeedriven** [comment]
It works fine with node if you use correct module name:

```
$ node
> require('card.js')
{ [Function]
  CARD_TYPES:
   [ { type: 'visa',
       numberRegex: /^4[0-9]{12}(?:[0-9]{3})?$/,
       iinNumberRegex: /^4/ },
     { type: 'mastercard',
```

**Comment by danielb2** [comment]
oops. well, I could have used that info sooner. I ended up going with another library
